### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Notlucky101** [BURN447/DartcraftReloaded#32]
when loading the server this message appears

ava.lang.NoClassDefFoundError: burn447/dartcraftReloaded/Items/Tools/ItemMagnetGlove
    at burn447.dartcraftReloaded.Items.ModItems.<clinit>(ModItems.java:39)
    at burn447.dartcraftReloaded.dartcraftReloaded$RegistrationHandler.registerItems(dartcraftReloaded.java:84)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_310_RegistrationHandler_registerItems_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:780)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: burn447.dartcraftReloaded.Items.Tools.ItemMagnetGlove
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 13 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/ItemMeshDefinition
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.ItemMeshDefinition
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 19 more
Caused by: java.lang.NullPointerException

**Comment by Brutalcreeper** [comment]
I have the exact same issue with my server through nitrado.

**Comment by BURN447** [comment]
Fixed with commit 4d3bcd4b13c1691d1f1f956b4564276a4d56fdcf and is included with the 1.12.2-2.3.1-Beta release
